spring:
  profiles:
    include: secret

  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 100MB

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        jdbc.batch_size: 1000
        order_inserts: true
        order_updates: true
        dialect: org.hibernate.dialect.MySQLDialect
        #        show_sql: true
        use_sql_comments: true
        jdbc:
          batch_versioned_data: true

default:
  news:
    image:
      url: "https://storage.googleapis.com/wave-app-bucket/default_news_image.png"

